services:
  whisper-api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: whisper-api
    ports:
      - "8000:8000"
    volumes:
      - ./model_storage:/models/whisper
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=transcriptions
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: transcriptions
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
