services:
  whisper-api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: whisper-api
    ports:
      - "8000:8000"
    volumes:
      - ./model_storage:/models/whisper
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=transcriptions
    depends_on:
      - db
    networks:
      - whisper_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"  # Проброс порта 80
    depends_on:
      - whisper-api
    networks:
      - whisper_network

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: transcriptions
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - whisper_network

volumes:
  db_data:

networks:
  whisper_network:
    driver: bridge
